# Assignment 01: Part-of-Speech (POS) Extraction from a News Article

**Name:** Bhagat Pandey
**Task:** Load a news article text file, perform POS tagging, and extract all Nouns and Verbs into a CSV file.

**Library used:** spaCy (`en_core_web_sm`)

## 1. Import libraries

In [ ]:
import spacy
import pandas as pd

nlp = spacy.load("en_core_web_sm")
print("spaCy version:", spacy.__version__)

spaCy version: 3.8.14

## 2. Load the news article

The article was downloaded/saved as a plain text file named `tiger.txt` in the same folder as this notebook.

In [ ]:
ARTICLE_PATH = 'chapter-01/tiger.txt'

with open(ARTICLE_PATH, "r", encoding="utf-8") as f:
    text = f.read()

In [ ]:
text

'KATHMANDU, JULY 29Nepal\'s wild tiger population has climbed to an estimated 429, up from 355 in 2022 and nearly four times the 121 recorded in 2010, the government announced on Wednesday as the country marked the 17th Global Tiger Day. The Ministry of Forests and Environment unveiled the findings of the National Tiger and Prey Base Survey 2026 in Kathmandu. The survey, conducted between December 2025 and July 2026 by the Department of National Parks and Wildlife Conservation and the Department of Forests and Soil Conservation, was supported by NTNC, WWF Nepal and ZSL Nepal.Chitwan National Park recorded the highest tiger population with 145, followed by Bardiya (112), Parsa (71), Banke (51) and Shuklaphanta (50). All five parks registered increases from the 2022 census, except Bardiya, whose population declined from 125 to 112.\nResearchers deployed around 1,100 camera traps across the Chitwan-Parsa, Banke-Bardiya and Shuklaphanta-Laljhadi landscapes, with about 250 personnel conducting systematic surveys and photographing tigers for at least 15 nights in each grid before analysing the images.Worldwide, the wild tiger population has increased from about 3,200 in 2010 to 5,357 in 2025. India remains home to the largest population with 3,167 tigers, followed by Russia (750), Indonesia (400) and Nepal, whose latest census now places it ahead of Indonesia.WWF Nepal Country Representative Dr Ghana Shyam Gurung hailed the rise as a "collective conservation achievement," crediting government leadership, community stewardship and collaboration across conservation partners.Conservationists cautioned that Nepal\'s forests are estimated to have a carrying capacity of around 400 tigers, meaning the latest population exceeds the habitat\'s sustainable limit.The increase has intensified concerns over human-tiger conflict, habitat fragmentation and poaching risks. Nepal currently has 16 "problem tigers"-animals involved in attacks, found injured or rescued from settlements-being housed in enclosures in Chitwan, Bardiya, Banke and the Central Zoo in Jawalakhel.To address the growing challenge, the government has proposed a 52-hectare Tiger Sanctuary in Devnagar, Chitwan, to rehabilitate injured and conflict-affected tigers while promoting eco-tourism.WWF Nepal said future efforts will focus on strengthening community forest user groups, buffer zone committees and local governments to improve coexistence.The organisation also plans to expand community-based monitoring, strengthen early warning systems and rapid response mechanisms, engage more young people in conservation, and mobilise greater private-sector investment.'

In [ ]:
text.split()

['KATHMANDU,',
 'JULY',
 "29Nepal's",
 'wild',
 'tiger',
 'population',
 'has',
 'climbed',
 'to',
 'an',
 'estimated',
 '429,',
 'up',
 'from',
 '355',
 'in',
 '2022',
 'and',
 'nearly',
 'four',
 'times',
 'the',
 '121',
 'recorded',
 'in',
 '2010,',
 'the',
 'government',
 'announced',
 'on',
 'Wednesday',
 'as',
 'the',
 'country',
 'marked',
 'the',
 '17th',
 'Global',
 'Tiger',
 'Day.',
 'The',
 'Ministry',
 'of',
 'Forests',
 'and',
 'Environment',
 'unveiled',
 'the',
 'findings',
 'of',
 'the',
 'National',
 'Tiger',
 'and',
 'Prey',
 'Base',
 'Survey',
 '2026',
 'in',
 'Kathmandu.',
 'The',
 'survey,',
 'conducted',
 'between',
 'December',
 '2025',
 'and',
 'July',
 '2026',
 'by',
 'the',
 'Department',
 'of',
 'National',
 'Parks',
 'and',
 'Wildlife',
 'Conservation',
 'and',
 'the',
 'Department',
 'of',
 'Forests',
 'and',
 'Soil',
 'Conservation,',
 'was',
 'supported',
 'by',
 'NTNC,',
 'WWF',
 'Nepal',
 'and',
 'ZSL',
 'Nepal.Chitwan',
 'National',
 'Park',
 'recorded',
 'the',
 'highest',
 'tiger',
 'population',
 'with',
 '145,',
 'followed',
 'by',
 'Bardiya',
 '(112),',
 'Parsa',
 '(71),',
 'Banke',
 '(51)',
 'and',
 'Shuklaphanta',
 '(50).',
 'All',
 'five',
 'parks',
 'registered',
 'increases',
 'from',
 'the',
 '2022',
 'census,',
 'except',
 'Bardiya,',
 'whose',
 'population',
 'declined',
 'from',
 '125',
 'to',
 '112.',
 'Researchers',
 'deployed',
 'around',
 '1,100',
 'camera',
 'traps',
 'across',
 'the',
 'Chitwan-Parsa,',
 'Banke-Bardiya',
 'and',
 'Shuklaphanta-Laljhadi',
 'landscapes,',
 'with',
 'about',
 '250',
 'personnel',
 'conducting',
 'systematic',
 'surveys',
 'and',
 'photographing',
 'tigers',
 'for',
 'at',
 'least',
 '15',
 'nights',
 'in',
 'each',
 'grid',
 'before',
 'analysing',
 'the',
 'images.Worldwide,',
 'the',
 'wild',
 'tiger',
 'population',
 'has',
 'increased',
 'from',
 'about',
 '3,200',
 'in',
 '2010',
 'to',
 '5,357',
 'in',
 '2025.',
 'India',
 'remains',
 'home',
 'to',
 'the',
 'largest',
 'population',
 'with',
 '3,167',
 'tigers,',
 'followed',
 'by',
 'Russia',
 '(750),',
 'Indonesia',
 '(400)',
 'and',
 'Nepal,',
 'whose',
 'latest',
 'census',
 'now',
 'places',
 'it',
 'ahead',
 'of',
 'Indonesia.WWF',
 'Nepal',
 'Country',
 'Representative',
 'Dr',
 'Ghana',
 'Shyam',
 'Gurung',
 'hailed',
 'the',
 'rise',
 'as',
 'a',
 '"collective',
 'conservation',
 'achievement,"',
 'crediting',
 'government',
 'leadership,',
 'community',
 'stewardship',
 'and',
 'collaboration',
 'across',
 'conservation',
 'partners.Conservationists',
 'cautioned',
 'that',
 "Nepal's",
 'forests',
 'are',
 'estimated',
 'to',
 'have',
 'a',
 'carrying',
 'capacity',
 'of',
 'around',
 '400',
 'tigers,',
 'meaning',
 'the',
 'latest',
 'population',
 'exceeds',
 'the',
 "habitat's",
 'sustainable',
 'limit.The',
 'increase',
 'has',
 'intensified',
 'concerns',
 'over',
 'human-tiger',
 'conflict,',
 'habitat',
 'fragmentation',
 'and',
 'poaching',
 'risks.',
 'Nepal',
 'currently',
 'has',
 '16',
 '"problem',
 'tigers"-animals',
 'involved',
 'in',
 'attacks,',
 'found',
 'injured',
 'or',
 'rescued',
 'from',
 'settlements-being',
 'housed',
 'in',
 'enclosures',
 'in',
 'Chitwan,',
 'Bardiya,',
 'Banke',
 'and',
 'the',
 'Central',
 'Zoo',
 'in',
 'Jawalakhel.To',
 'address',
 'the',
 'growing',
 'challenge,',
 'the',
 'government',
 'has',
 'proposed',
 'a',
 '52-hectare',
 'Tiger',
 'Sanctuary',
 'in',
 'Devnagar,',
 'Chitwan,',
 'to',
 'rehabilitate',
 'injured',
 'and',
 'conflict-affected',
 'tigers',
 'while',
 'promoting',
 'eco-tourism.WWF',
 'Nepal',
 'said',
 'future',
 'efforts',
 'will',
 'focus',
 'on',
 'strengthening',
 'community',
 'forest',
 'user',
 'groups,',
 'buffer',
 'zone',
 'committees',
 'and',
 'local',
 'governments',
 'to',
 'improve',
 'coexistence.The',
 'organisation',
 'also',
 'plans',
 'to',
 'expand',
 'community-based',
 'monitoring,',
 'strengthen',
 'early',
 'warning',
 'systems',
 'and',
 'rapid',
 'response',
 'mechanisms,',
 'engage',
 'more',
 'young',
 'people',
 'in',
 'conservation,',
 'and',
 'mobilise',
 'greater',
 'private-sector',
 'investment.']

In [ ]:
len(text.split())

370

## 3. Perform POS tagging

In [ ]:
doc = nlp(text)

In [ ]:
doc

KATHMANDU, JULY 29Nepal's wild tiger population has climbed to an estimated 429, up from 355 in 2022 and nearly four times the 121 recorded in 2010, the government announced on Wednesday as the country marked the 17th Global Tiger Day. The Ministry of Forests and Environment unveiled the findings of the National Tiger and Prey Base Survey 2026 in Kathmandu. The survey, conducted between December 2025 and July 2026 by the Department of National Parks and Wildlife Conservation and the Department of Forests and Soil Conservation, was supported by NTNC, WWF Nepal and ZSL Nepal.Chitwan National Park recorded the highest tiger population with 145, followed by Bardiya (112), Parsa (71), Banke (51) and Shuklaphanta (50). All five parks registered increases from the 2022 census, except Bardiya, whose population declined from 125 to 112.
Researchers deployed around 1,100 camera traps across the Chitwan-Parsa, Banke-Bardiya and Shuklaphanta-Laljhadi landscapes, with about 250 personnel conducting systematic surveys and photographing tigers for at least 15 nights in each grid before analysing the images.Worldwide, the wild tiger population has increased from about 3,200 in 2010 to 5,357 in 2025. India remains home to the largest population with 3,167 tigers, followed by Russia (750), Indonesia (400) and Nepal, whose latest census now places it ahead of Indonesia.WWF Nepal Country Representative Dr Ghana Shyam Gurung hailed the rise as a "collective conservation achievement," crediting government leadership, community stewardship and collaboration across conservation partners.Conservationists cautioned that Nepal's forests are estimated to have a carrying capacity of around 400 tigers, meaning the latest population exceeds the habitat's sustainable limit.The increase has intensified concerns over human-tiger conflict, habitat fragmentation and poaching risks. Nepal currently has 16 "problem tigers"-animals involved in attacks, found injured or rescued from settlements-being housed in enclosures in Chitwan, Bardiya, Banke and the Central Zoo in Jawalakhel.To address the growing challenge, the government has proposed a 52-hectare Tiger Sanctuary in Devnagar, Chitwan, to rehabilitate injured and conflict-affected tigers while promoting eco-tourism.WWF Nepal said future efforts will focus on strengthening community forest user groups, buffer zone committees and local governments to improve coexistence.The organisation also plans to expand community-based monitoring, strengthen early warning systems and rapid response mechanisms, engage more young people in conservation, and mobilise greater private-sector investment.

In [ ]:
# Preview a few tokens with their POS tags
for token in list(doc)[:15]:
    print(f"{token.text:<15} {token.pos_:<10} {token.tag_}")

KATHMANDU       PROPN      NNP
,               PUNCT      ,
JULY            PROPN      NNP
29Nepal         PROPN      NNP
's              PART       POS
wild            ADJ        JJ
tiger           NOUN       NN
population      NOUN       NN
has             AUX        VBZ
climbed         VERB       VBN
to              ADP        IN
an              DET        DT
estimated       VERB       VBN
429             NUM        CD
,               PUNCT      ,

## 4. Extract all Nouns and Verbs

spaCy's coarse `pos_` attribute labels tokens as `NOUN`, `PROPN` (proper noun), `VERB`, etc.
Here we keep `NOUN`, `PROPN`, and `VERB` tokens, skipping punctuation and whitespace.

In [ ]:
target_pos = {"NOUN", "PROPN", "VERB"}

records = []
for token in doc:
    if token.pos_ in target_pos and token.is_alpha:
        records.append({
            "Word": token.text,
            "POS_Tag": token.pos_,
            "Detailed_Tag": token.tag_,
        })

df = pd.DataFrame(records)
print(f"Extracted {len(df)} noun/verb tokens.")
df.head(15)

Extracted 210 noun/verb tokens.

          Word POS_Tag Detailed_Tag
0    KATHMANDU   PROPN          NNP
1         JULY   PROPN          NNP
2        tiger    NOUN           NN
3   population    NOUN           NN
4      climbed    VERB          VBN
5    estimated    VERB          VBN
6        times    NOUN          NNS
7     recorded    VERB          VBN
8   government    NOUN           NN
9    announced    VERB          VBD
10   Wednesday   PROPN          NNP
11     country    NOUN           NN
12      marked    VERB          VBD
13      Global   PROPN          NNP
14       Tiger   PROPN          NNP

## 5. Quick summary of counts by POS category

In [ ]:
summary = df["POS_Tag"].value_counts()
summary

POS_Tag
NOUN     85
PROPN    72
VERB     53
Name: count, dtype: int64

## 6. Save extracted words to CSV

In [ ]:
OUTPUT_CSV = "BhagatPandey_POS_01.csv"

df[["Word", "POS_Tag"]].to_csv(OUTPUT_CSV, index=False)
print(f"Saved {len(df)} rows to {OUTPUT_CSV}")

Saved 210 rows to BhagatPandey_POS_01.csv